
trigger:
- main

pool:
  name: awspool

steps:
- script: |
    echo "Agent: $(Agent.Name)"
    echo "Pool: $(Agent.JobName)"
    whoami || id
    echo "Repo checked out to: $(Build.SourcesDirectory)"
